apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-web'
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: '{{ .Values.web.hostname }}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ .Release.Name }}-web'
            port:
              name: "web"
  {{- if .Values.web.tls.enabled }}
  tls:
  - hosts:
    - '{{ .Values.web.hostname }}'
    secretName: {{ .Release.Name }}-cert
  {{- end }}